### PR TITLE
Package riak_cs_control with new node_package features

### PR DESCRIPTION
**Pull request by jaredmorrow**
In addition to packaging changes that brought
riak_cs_control up to par with riak_cs, the general
naming of the installed application changed from
riak_cs_control to riak-cs-control.  This change can
be seen in both rel and package builds.

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
It looks like this package doesn't contain the last PR, can you confirm?

**Comment by jaredmorrow** [comment]
Correct it was branched from master before the last commit.

**Comment by cmeiklejohn** [comment]
Can you cut a new package?  This will not start without that fix.

**Comment by jaredmorrow** [comment]
Yes, I'll merge in master and build a new set tonight.

**Comment by cmeiklejohn** [comment]
Thanks.

**Comment by cmeiklejohn** [comment]
:+1:

**Pull request merged**
