### PR TITLE
Create users.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
Please merge before #10.

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Assigning @kellymclaughlin.

**Comment by kellymclaughlin** [comment]
Creating the user works, but when it redirects me back the user listing page the new user is not displayed and I have to refresh the page for them to show up.

**Comment by cmeiklejohn** [comment]
Weird, let me look into that.

**Comment by cmeiklejohn** [comment]
@kellymclaughlin this should address the issue above, the solution isn't perfect, but it's the only thing that works at this point.

**Comment by kellymclaughlin** [comment]
Yep, wfm now. +1 to merge.

**Pull request merged**
